version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8086:80" # client
            - "8087:81" # app
        volumes:
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
            - ./client:/var/www
        links:
            - app

    app:
        build: ./.docker/php
        volumes:
            - ./app:/app
            - .docker/php/.bashrc:/var/www/.bashrc
        ports:
            - "9000:9000"

#    client:
#        build: ./.docker/node
#        volumes:
#            - ./client:/app

#mysql:
#    image: mysql:5.7
#    volumes:
#        - "./mysqldata/db:/var/lib/mysql"
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123
#      MYSQL_DATABASE: cmv
#      MYSQL_USER: homestead
#      MYSQL_PASSWORD: secret
#    ports:
#        - "3306:3306"

#beanstalkd:
#    image: agaveapi/beanstalkd
#    ports:
#        - "11300:11300"
#redis:
#    image: redis
#    ports:
#        - "6379:6379"
#    volumes:
#        - "./redisdata/db:/data"

# selenium:
#     image: selenium/standalone-chrome
#     ports:
#       - 4444:4444
